server:
  port: 8082
  servlet:
    context-path: /world

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/world
    username: rob
    password: dog123Pup

